### ISSUE TITLE
Segmentation fault with midgard2 - mayb due to recursion ?

### ISSUE THREAD

**Issue by gudd** [midgardproject/midgard-php5#118]
HI there,

i'm using PHP5.3.10 on two installations - one running with midgard1 the other with midgard2.
I have the same phpunit tests running on both machines , but in the midgard2 machine i get a Segmentation fault. He is running out of memory - i assume due some looping in the midgard-class.

In valgrind returns this:
httpshttps://gist.github.com/gudd/6684906

In GDB i only receive this:

Program received signal SIGSEGV, Segmentation fault.
0x105ba9e0 in ?? ()
(gdb) bt
#0  0x105ba9e0 in ?? ()
#1  0x0831c8e8 in _zval_copy_ctor_func ()
#2  0x08330fb9 in ?? ()
#3  0x08332c08 in zend_fetch_debug_backtrace ()
#4  0x08336c26 in ?? ()
#5  0x08336d0a in ?? ()
#6  0x08320d96 in _object_and_properties_init ()
#7  0x08320eab in _object_init_ex ()
#8  0x0834ab87 in ?? ()
#9  0x0834611e in execute ()
#10 0x0831046c in zend_call_function ()
#11 0x081a1e3e in ?? ()
#12 0x08396d6a in ?? ()
#13 0x0834611e in execute ()
#14 0x0831ede9 in zend_execute_scripts ()
#15 0x082c54ae in php_execute_script ()
#16 0x0806b761 in ?? ()
#17 0xb78604d3 in __libc_start_main (main=0x8069e90, argc=3, ubp_av=0xbffff784, init=0x83b7700 <__libc_csu_init>,

```
fini=0x83b7770 <__libc_csu_fini>, rtld_fini=0xb7fed280 <_dl_fini>, stack_end=0xbffff77c) at libc-start.c:226
```
#18 0x0806b805 in _start ()

Is there something i missed ?
If you need futher infos please also let me know - any help is appreciated.

regards

**Comment by piotras** [comment]
Segfault is not catched by valgrind unfortunately :/
Take a look at this issue: https://github.com/midgardproject/midgard-php5/issues/50.
There are notes how to initialize valgrind and what ini settings should be used.

Do you know what PHP code is executed when segfault appears?
